# Tarea 1
Determinar la media (y moda) de la anchura de los pétalos. Y generar una tabla identica a la propuesta para cepalos y petalos.
- Pineda Hernández Francisco
- Grupo 5AM1

Importamos las librerías necesarias para la carga y manipulación del Dataset.

In [47]:
from sklearn import datasets
import pandas as pd
import numpy as np

Desplegamos la información general del atributo .data para visualizar los vectores de características de cada variable.

In [48]:
iris = datasets.load_iris()
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

Desplegamos el atributo .target para visualizar las etiquetas

In [49]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Analizamos los nombres de las etiquetas y de las variables para buscar nuestras variables de interes.

In [50]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

Analizamos por medio de las funciones propuestas por Numpy y por Statistics los valores de media y moda para cada una de las variables en el Dataset de iris, incluida la <b>anchura de los sepalos</b>.

In [51]:
import statistics as stat
for i in range(0, 4):
    print(f"{i}.-Nombre de la variable:\t{iris.feature_names[i]}\tmedia: {np.median(iris.data[:, i])}\tmoda: {stat.mode(iris.data[:, i])}")

0.-Nombre de la variable:	sepal length (cm)	media: 5.8	moda: 5.0
1.-Nombre de la variable:	sepal width (cm)	media: 3.0	moda: 3.0
2.-Nombre de la variable:	petal length (cm)	media: 4.35	moda: 1.4
3.-Nombre de la variable:	petal width (cm)	media: 1.3	moda: 0.2

Con lo anterior podemos identificar que la variable la cual posee una media de 1.3 es la relacionada a "petal width (cm)", la cuál se encuentra en la posición 3 del conjunto de datos cargado.

Sabiendo lo anterior podemos proceder a generar la función la cuál será usada para el analisis en la primer tabla solicitada.

In [52]:
def generar_tabla(caracteristica_iris):
    # PRIMER PARTE DE LA TABLA
    valores_intervalo1 = np.arange(min(caracteristica_iris), round(np.median(caracteristica_iris + 0.1), 1), 0.1) # se define el intervalo de 0.1 en 0.1 desde 0 hasta 2.5
    valores_intervalo1 = [round(valor, 1) for valor in valores_intervalo1]

    array_relativa1 = []
    array_acumulada1 = []

    acumulada1 = 0
    for valor_intervalo in valores_intervalo1:
        relativa = 0
        for petal_width in sorted(caracteristica_iris)[:75]:
            if valor_intervalo == petal_width:
                relativa = relativa + 1
        array_relativa1.append(relativa)
        acumulada1 = acumulada1 + relativa
        array_acumulada1.append(acumulada1)

    # SEGUNDA PARTE DE LA TABLA
    valores_intervalo2 = np.arange(max(caracteristica_iris), round(np.median(caracteristica_iris - 0.1), 1), -0.1) # se define el intervalo de 0.1 en 0.1 desde 0 hasta 2.5
    valores_intervalo2 = [round(valor, 1) for valor in valores_intervalo2]

    array_relativa2 = []
    array_acumulada2 = []

    acumulada2 = 0
    for valor_intervalo in valores_intervalo2:
        relativa = 0
        for petal_width in sorted(caracteristica_iris)[75:]:
            if valor_intervalo == petal_width:
                relativa = relativa + 1
        array_relativa2.append(relativa)
        acumulada2 = acumulada2 + relativa
        array_acumulada2.append(acumulada2)

    # Crear DataFrame
    tabla = pd.DataFrame({
    'Valor': valores_intervalo1,
    'Total': array_relativa1,
    'Acumulado': array_acumulada1,
    'Valor2': valores_intervalo2,
    'Total2': array_relativa2,
    'Acumulado2': array_acumulada2
    })

    return tabla

Obtenemos el vector del ancho de los petalos (petal_widths) usnado slicing.

## Tabla 1 (ancho de los petalos):

In [53]:
petal_widths = iris.data[:, 3] # se obtiene el arrglo de valores para el ancho del petalo
generar_tabla(petal_widths)

    Valor  Total  Acumulado  Valor2  Total2  Acumulado2
0     0.1      5          5     2.5       3           3
1     0.2     29         34     2.4       3           6
2     0.3      7         41     2.3       8          14
3     0.4      7         48     2.2       3          17
4     0.5      1         49     2.1       6          23
5     0.6      1         50     2.0       6          29
6     0.7      0         50     1.9       5          34
7     0.8      0         50     1.8      12          46
8     0.9      0         50     1.7       2          48
9     1.0      7         57     1.6       4          52
10    1.1      3         60     1.5      12          64
11    1.2      5         65     1.4       8          72
12    1.3     10         75     1.3       3          75

Creamos una segunda función para la tabla dos ya que las indicaciones especificas de la tabla 1 y las diferencias en la distribución de los datos a partir de las medianas no coincide al generar los tamaños iguales de los arreglos.

In [54]:
def generar_tabla2(caracteristica_iris):
    # PRIMER PARTE DE LA TABLA
    valores_intervalo1 = np.arange(min(caracteristica_iris), (min(caracteristica_iris) + max(caracteristica_iris))/2, 0.1) # se define el intervalo de 0.1 en 0.1 desde 0 hasta 2.5
    valores_intervalo1 = [round(valor, 1) for valor in valores_intervalo1]

    array_relativa1 = []
    array_acumulada1 = []

    acumulada1 = 0
    for valor_intervalo in valores_intervalo1:
        relativa = 0
        for petal_width in sorted(caracteristica_iris)[:75]:
            if valor_intervalo == petal_width:
                relativa = relativa + 1
        array_relativa1.append(relativa)
        acumulada1 = acumulada1 + relativa
        array_acumulada1.append(acumulada1)

    # SEGUNDA PARTE DE LA TABLA
    valores_intervalo2 = np.arange(max(caracteristica_iris), (min(caracteristica_iris) + max(caracteristica_iris))/2, -0.1) # se define el intervalo de 0.1 en 0.1 desde 0 hasta 2.5
    valores_intervalo2 = [round(valor, 1) for valor in valores_intervalo2]

    array_relativa2 = []
    array_acumulada2 = []

    acumulada2 = 0
    for valor_intervalo in valores_intervalo2:
        relativa = 0
        for petal_width in sorted(caracteristica_iris)[75:]:
            if valor_intervalo == petal_width:
                relativa = relativa + 1
        array_relativa2.append(relativa)
        acumulada2 = acumulada2 + relativa
        array_acumulada2.append(acumulada2)

    # Crear DataFrame
    tabla = pd.DataFrame({
    'Valor': valores_intervalo1,
    'Total': array_relativa1,
    'Acumulado': array_acumulada1,
    'Valor2': valores_intervalo2,
    'Total2': array_relativa2,
    'Acumulado2': array_acumulada2
    })

    return tabla

## Tabla 2 (ancho de los sepalos):

In [55]:
sepal_widths = iris.data[:, 1]
generar_tabla2(sepal_widths)

    Valor  Total  Acumulado  Valor2  Total2  Acumulado2
0     2.0      1          1     4.4       1           1
1     2.1      0          1     4.3       0           1
2     2.2      3          4     4.2       1           2
3     2.3      4          8     4.1       1           3
4     2.4      3         11     4.0       1           4
5     2.5      8         19     3.9       2           6
6     2.6      5         24     3.8       6          12
7     2.7      9         33     3.7       3          15
8     2.8     14         47     3.6       4          19
9     2.9     10         57     3.5       6          25
10    3.0     18         75     3.4      12          37
11    3.1      0         75     3.3       6          43
12    3.2      0         75     3.2      13          56